// lib/dummy-data.ts
// ... (Konten yang sudah ada tetap dipertahankan)

import { TokoExistingItem } from "@/types/toko_existing";

export const dummyTokoExistingData: TokoExistingItem[] = [
  {
    id: 101,
    nama_toko: "Toko Meruya Selatan",
    alamat: "Jl. Meruya Selatan No. 10",
    regional: "Jakarta Barat",
    tahun_beroperasi: 2020,
    status: "Active",
    gambar_url: "/images/toko-meruya.jpg",
  },
  {
    id: 102,
    nama_toko: "Toko Bintaro Sektor 9",
    alamat: "Jl. Maleo Raya Blok C9",
    regional: "Tangerang Selatan",
    tahun_beroperasi: 2018,
    status: "Active",
    gambar_url: "/images/toko-bintaro.jpg",
  },
  {
    id: 103,
    nama_toko: "Toko Cikarang Utara",
    alamat: "Ruko Sentral Cikarang",
    regional: "Bekasi",
    tahun_beroperasi: 2023,
    status: "Pending",
    gambar_url: "/images/toko-cikarang.jpg",
  },
  {
    id: 104,
    nama_toko: "Toko Bogor Raya",
    alamat: "Jl. Raya Padjajaran No. 5",
    regional: "Bogor",
    tahun_beroperasi: 2020,
    status: "Active",
    gambar_url: "/images/toko-bogor.jpg",
  },
  {
    id: 105,
    nama_toko: "Toko Pondok Indah",
    alamat: "Jl. Metro Pondok Indah",
    regional: "Jakarta Selatan",
    tahun_beroperasi: 2024,
    status: "Inactive",
    gambar_url: "/images/toko-pondokindah.jpg",
  },
  {
    id: 106,
    nama_toko: "Toko Serpong Boulevard",
    alamat: "Ruko Serpong Boulevard",
    regional: "Tangerang Selatan",
    tahun_beroperasi: 2018,
    status: "Active",
    gambar_url: "/images/toko-serpong.jpg",
  },
  {
    id: 107,
    nama_toko: "Toko Kelapa Gading",
    alamat: "Jl. Raya Kelapa Gading",
    regional: "Jakarta Utara",
    tahun_beroperasi: 2023,
    status: "Active",
    gambar_url: "/images/toko-kelapagading.jpg",
  },
  {
    id: 108,
    nama_toko: "Toko Depok Margonda",
    alamat: "Jl. Margonda Raya No. 100",
    regional: "Depok",
    tahun_beroperasi: 2021,
    status: "Active",
    gambar_url: "/images/toko-depok.jpg",
  },
  {
    id: 109,
    nama_toko: "Toko Bekasi Square",
    alamat: "Jl. Jend. Sudirman",
    regional: "Bekasi",
    tahun_beroperasi: 2021,
    status: "Active",
    gambar_url: "/images/toko-bekasi.jpg",
  },
  {
    id: 110,
    nama_toko: "Toko Senayan City",
    alamat: "Jl. Asia Afrika",
    regional: "Jakarta Pusat",
    tahun_beroperasi: 2022,
    status: "Active",
    gambar_url: "/images/toko-senayan.jpg",
  },
  {
    id: 111,
    nama_toko: "Toko Cibubur Junction",
    alamat: "Jl. Transyogi",
    regional: "Bogor",
    tahun_beroperasi: 2024,
    status: "Pending",
    gambar_url: "/images/toko-cibubur.jpg",
  },
];
